### ISSUE TITLE
Aspera/SRAtoolkit failing

### ISSUE THREAD

**Issue by mtmcgowan** [SystemsGenetics/GEMmaker#103]
GEMmaker is failing at the Aspera step.

Here is the error I am seeing:
NOTE: Process `ascp (ERX1659439)` terminated with an error exit status (1) -- Error is ignored

Here's a subset of my remote sample input file:
ERR1588790
ERR1588791
ERR1588792
ERR1588793
ERR1588794

I tried rerunning GEMmaker with the SRAtoolkit option and got another error:
NOTE: Process `prefetch (**ERX**1659517)` terminated with an error exit status (127) -- Error is ignored

When I manually run this command in a SLUM idev session I get more information:
prefetch.2.8.0 err: path not found while resolving tree within virtual file system module - 'ERX1659522' cannot be found.

If I manually rerun this command with the sample '**ERR**' prefix instead of '**ERX**' it seems to run fine:
prefetch ERR1659522
2019-03-15T22:14:20 prefetch.2.8.0: 1) Downloading 'ERR1659522'...
2019-03-15T22:14:20 prefetch.2.8.0:  Downloading via http...

**Comment by JohnHadish** [comment]
Issue with Kamiak environment
