### ISSUE TITLE
fastq_merge very inefficient

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#108]
The fastq_merge process will always cat files into a new file, even if there is only one srr run. This means that the storage space required for the files doubles. This makes execution on local machines difficult when you are doubling several 50G files, which limits the user to running with a queue size of only 1 or 2. 

While the option to delete the downloaded files is implemented with #67, the issue is that nextflow tends to complete all tasks in one section before moving on. This means that if a user is trying to do 4 50G files, their footprint will more than likely expand to greater than 400G before it is reduced.

I am not sure if there is an elegant way around this.

**Comment by JohnHadish** [comment]
https://github.com/nextflow-io/nextflow/issues/452

**Comment by spficklin** [comment]
What about adjusting the code to not copy but create a hard link if there is only one SRR file?

**Comment by bentsherman** [comment]
Or just rename the file if there's only one SRR.

**Comment by spficklin** [comment]
I believe this issue is correct as per the merged PR. Closing
