### ISSUE TITLE
Confusing naming of input reference files

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#109]
I was just helping someone run GEMmaker, and realized that the input naming file format for Kallisto and Salmon is confusing. While it makes sense to have a prefix for hisat2, it does not make sense for the others. 

I am going to change this so that hisat2, salmon, and kallisto have separate sections. Probably will look something like this:

```
hisat_file_reference_path = ""
hisat2_prefix = ""


salmon_reference_file_fullpath = ""
kallisto_reference_file_fullpath = ""
```
I am just writing this so I don't forget to do it later.

**Comment by spficklin** [comment]
We've reorganized the naming of the indexes in the config file in a different PR (can't remember which one or I'd link to it).
