### ISSUE TITLE
need Clean Gene Abundance File

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#110]
.ga files are made in Kallisto and Salmon, but not Hisat2. Currently, there is no cleanup for them. This is not a big issue at a small number of runs, but gets to be an issue as more are processed.

Here is an image of a run that was done on Irods of the 1001 Arabidopsis experiment using kallisto. The y axis is usage of space, the x is time. This records the entire footprint of GEMmaker (all directories) for a run that has all cleanup turned on.
![image](https://user-images.githubusercontent.com/35115540/58838732-60063c00-8614-11e9-91e8-e1cc49269871.png)
The .ga files are the majority of the space used at the end. This should be an easy fix, as it is just copying a cleanup process. Just writing this so I remember to do it.

**Comment by spficklin** [comment]
Yes, we need to fix this.

**Comment by bentsherman** [comment]
On a related note, do we need to save the GTF file created by stringtie? It looks like it is only used to generate raw counts for hisat2, and it also takes up a good bit of space.

**Comment by spficklin** [comment]
I don't think so. As long as we get the data out of it into the FPKM/TPM files we can get rid of it.

**Comment by spficklin** [comment]
Closing this as the PR is merged.
