### ISSUE TITLE
Need a way to exclude samples

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#111]
With the Ath26K experiment I have a sample that trimmomatic cannot determine the encoding.  I think given the size of the data I want to just skip it.  I can't set the `errorStrategy` to ignore because then the sample never gets cleaned out of the `work/GEMmaker/process` directory and as errors like this occur it eats up an available execution slot.  If this problems happens enough the workflow will stop as it the 'process' folder gets clogged, but GEMmaker never fails. It just hangs waiting for a sample to finish but they never do because they get ignored.

I propose we support inclusion of a file for listing samples to skip. This way when the workflow fails, we can add the same to the skip file and the workflow won't try to include it in subsequent runs.

**Comment by spficklin** [comment]
@bentsherman I added a fix to this issue that lets us skip a bad sample.  I'm not sure how you would want that integrated it into your `main-e2e.nf` could you take a look?   The branch is named `111-skip_samples`

**Comment by bentsherman** [comment]
I think I can just have `main-e2e.nf` behave exactly the same as before, because it can ignore failed samples without the problems that you mentioned. If it's not too hard I'll also implement this skip samples list for `main-e2e.nf` as well, so that the option at least works for both scripts. Probably won't be until next week when I get back to the lab.

**Comment by spficklin** [comment]
Okay no rush.  Once you're done we can submit the PR.  Thanks @bentsherman

**Comment by bentsherman** [comment]
I've added my fixes for main-e2e.nf. I won't bother implementing this option for main-e2e.nf for now because it's not really an issue with the e2e method. Also we may want to merge the k8s fixes PR before this one as there will likely be some small merge conflicts.

**Comment by spficklin** [comment]
Issue fixed and merged.
