### ISSUE TITLE
How to stage input data

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#115]
Currently, the default config points explicitly to the example input files, which is nice because it's easy to run the example workflow out of the box, but there is an inconvenience in that these settings must be changed every time the input data is changed. Actually this seemed like a totally normal step to me until I figured out a better way while working on my other pipelines.

Consider this example from the KINC-nf workflow:
```
# nextflow.config
params {
  input_dir = "input"
}

# main.nf
EMX_FILES_FROM_INPUT = Channel.fromFilePairs("${params.input_dir}/*.emx", size: 1, flat: true)
```

This channel expression will grab every EMX file in the input directory and tag it by it's name (whatever is in the glob character). So if you want to process different GEMs, you just move whatever GEMs you want in and out of the input directory. No config changes necessary! If you take a deeper look you'll see that I use that pattern several times both for KINC-nf and gene-oracle-nf. I like this approach because it reinforces the task of staging your input data.

Unfortunately the input data for GEMmaker is more complex than for KINC, so I don't know if I can eliminate all of the necessary changes to the config file... but I would like to work towards that point. So here's what I'm thinking:
```
# nextflow.config
params {
  input {
    dir = "input"
    remote_sample_list = "SRA_IDs.txt"
    local_sample_files = "*_{1,2}.fastq"

    hisat2 {
      enabled = true
      indexes_dir = "reference/*.transcripts.hisat.indexes"
      gtf_file = "reference/*.transcripts.gtf"
    }
    salmon {
      enabled = false
      index_file = "reference/*.transcripts.Salmon.indexed"
    }
    kallisto {
      enabled = false
      index_file = "reference/*.transcripts.Kallisto.indexed"
    }
  }
}

# main.nf
LOCAL_SAMPLE_FILES = Channel.fromFilePairs("${params.input.dir}/${params.input.local_sample_files}", size: -1)
SRR_FILE = Channel.fromPath("${params.input.dir}/${params.input.remote_sample_list}")
```

With this schema, we would keep the example data as it is, although with a simpler directory structure:
```
examples/
  CORG/
    reference/
    SRA_IDs.txt
    *.fastq
```

To run the example, the user simply does:
```
mkdir -p input
mv examples/CORG/* input

nextflow run main.nf -with-docker
```

And to switch to real data, they move the example data out, and the real data into the input directory. I think it is much more intuitive to move data around like this instead of changing the config file to point to different locations.

The main issue that remains is how to properly capture the reference files, but I'm going to wait for #109 to be resolved before deciding what to do here.

**Comment by JohnHadish** [comment]
I agree that it is more intuitive to move the files into an input directory. We could just ship GEMmaker with the example in the input directory to start out with. Of course, this would mean that the user would have to delete them before they did their own files, but I think that is probably acceptable.

This is the same format that is used in the OSG KINC workflow as well.

**Comment by JohnHadish** [comment]
Just thought of this, we could also just have a directory for the reference files as well

**Comment by spficklin** [comment]
This is fixed and merged.
