### ISSUE TITLE
Generating a Gene Length File for additional normalization

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#121]
GEMmaker currently offers 3 different output formats, TPM, FPKM, and RAW. Some users may wish to use a different normalization method than these, however. To do a different normalization technique, the user typically needs the RAW file and the read length of each gene. This information is contained in the reference files for each of our alignment tools, as well as in the ".ga" or ".gtf" output files. It is in different formats for each tool:

Hisat2:
```
Gene ID	Gene Name	Reference	Strand	Start	End	Coverage	FPKM	TPM
gene_Alpha	Alpha_encoder	Chr1	.	1	100	17.500000	2500000.000000	250000.000000
gene_Beta	Beta_transcription_factor	Chr1	.	140	239	35.000000	5000000.000000	500000.000000
gene_Zeta	Zeta_chloroplasts	Chr2	.	1	100	17.500000	2500000.000000	250000.000000
gene_Epsilon	Epsilon_rubisco	Chr3	.	204	305	0.0	0.0	0.0
gene_Gamma	Gamma_rubisco	Chr3	.	1	101	0.0	0.0	0.0
gene_Delta	Delta_rubisco	Chr3	.	102	203	0.0	0.0	0.0
```

Kallisto:
```
target_id	length	eff_length	est_counts	tpm
Alpha.1	100	31	25	240385
Beta.1	100	31	50	480769
Zeta.1	100	31	29	278846
Gamma.1	101	32	0	0
Delta.1	102	33	0	0
Epsilon.1	102	33	0	0
```

Salmon:
```
Name	Length	EffectiveLength	TPM	NumReads
Alpha.1	100	4.495	240384.615385	25.000
Beta.1	100	4.495	480769.230769	50.000
Zeta.1	100	4.495	278846.153846	29.000
Gamma.1	101	4.519	0.000000	0.000
Delta.1	102	4.543	0.000000	0.000
Epsilon.1	102	4.543	0.000000	0.000
```

For this improvement, we need to investigate standard formats that various normalization tools use for their read lengths, and generate an optional file for this. This would make it easier for the user, as they would not need to dig into the intermediary files or reference files to retrieve this information.

Possible format:
```
target_id	length
Alpha.1	100	
Beta.1	100	
Zeta.1	100	
Gamma.1	101	
Delta.1	102	
Epsilon.1	102
```

This was requested by @biggstd for his gene selector program.

**Comment by spficklin** [comment]
Given a lack of time and other work arounds. I'm closing this out.
