### ISSUE TITLE
reference_name

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#124]
we should replace the `reference_name` argument in the nextflow.config file with a genome metadata section that has the: genus, species, infraspecific_name, assembly version and annotation version.

**Comment by spficklin** [comment]
We need updates to Pynome and access to these files somewhere public to make this happen.

**Comment by JohnHadish** [comment]
When we implement this, I think that it would be beneficial to require the user to change the parameters. This would eliminate the issues seen in #158. 

When a user does not change the parameters from the default CORG, and are running different files, GEMmaker would throw the error:
```
Error: You are using Default Genome Metadata Parameters to run this file. This will result in incorrect metadata. Please modify the genome metadata section in the nextflow.config.

Execution is Halted
```

**Comment by spficklin** [comment]
This is definitely on our radar with Pynome but we don't need the issue hanging out forever.  So, I'm closing.
