### ISSUE TITLE
Determine max-number of processes to run at the same time automatically

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#128]
This is just an idea I wanted to get down so that I do not forget it. 

Currently I am trying to run GEMmaker on my local machine. I have currently ran into an issue twice of filling up all the space on my machine. This is due to the fact that there is a point where both downloaded fastq and cleaned fastq files exist at the same time. 

This takes up a large amount of room, especially when the downloading is the bottle neck. The processes appear to sync up, which results in all of them having their most expensive (in terms of space useage) at the same time. 

What I think we should consider adding is a tool that determines the size of the files, and estimates how much room these would take up at their max size in the pipeline. GEMmaker would then automatically limit the number of instances running at the same time to hold it at less than what the user has.

It is really annoying when your tool fails to overload and you have to start all over with fewer instances.

**Comment by bentsherman** [comment]
This is related to another idea I had about estimating the runtime for GEMmaker. I think if we know the number of runs for each SRR input, we can determine the file size and then probably predict the runtime as a bonus. So if we could expand the sra metadata script or perhaps make a separate script, to query the run sizes, we could make this work.

**Comment by spficklin** [comment]
Given we don't have time to implement this, I'm going to close this out. But if anyone feels strongly about it and wants to try and implement it, please reopen.
