### ISSUE TITLE
Nextflow Version 19.07.0 depreciates "create"

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#129]
Here is the warning message:
```
WARN: The channel `create` method is deprecated -- it will be removed in a future release
```
Upgraded versions to solve issue with download speed: https://github.com/nextflow-io/nextflow/issues/1206
And saw that this was now depreciated. The nextflow documentation does not yet reflect this, however.

**Comment by JohnHadish** [comment]
https://github.com/nextflow-io/nextflow/issues/1269

**Comment by JohnHadish** [comment]
This needs to wait until DSL 2 has a consistent syntax established, otherwise we are going to have to fix it all over again: https://www.nextflow.io/docs/edge/dsl2.html. For now, Paolo has said that channel create will continue to exist (see previous comment)

**Comment by spficklin** [comment]
No more issues with this with the nf-core compatibility.
