### ISSUE TITLE
`write_stage_files` Does not find all of the samples from remote list

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#130]
The file I gave to GEMmaker contains 934 samples, but GEMmaker does not always find all of these during the `write_stage_file`. From two different runs:
```
[d5/dab185] process > write_stage_files (SRX1897421)           [100%] 780 of 780 ✔
```
```
[43/24f663] process > write_stage_files (SRX4114881)          [100%] 930 of 930 ✔
```

Running with command:
```
nextflow run main.nf -profile standard -with-singularity
```

**Comment by spficklin** [comment]
I have just been able to reproduce this problem. It doesn't always occur.  But what I observed was that the `retrieve_sra_metadat.py` script did not fully get information for all of the samples. There's no error messages to point to a problem from that script, so I'll have to dig into it.

**Comment by spficklin** [comment]
Fixed with PR.  Closing
