### ISSUE TITLE
DockerHub Org for GEMmaker

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#132]
Right now we are pushing all of the docker images to the systemsgenetics dockerhub organization.  However, we're now working on the AnnoTater workflow which also creates docker images.  These images are customized for the workflow they service and we may need at some point to use the same software but to have it configured differently for different workflows.  I suggest we create a GEMmaker organization on DockerHub and we push all of the images there.  

It would require we change all of the images from `systemsgenetics/<program>:<version>` to `gemmaker/<program>:<version>`

I have already created the organization, but will wait to change things in the event someone disagrees.

**Comment by bentsherman** [comment]
Sounds good to me.

**Comment by spficklin** [comment]
PR merged!
