### ISSUE TITLE
Update issue 138's python library so that it can run with singularity

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#139]
138 does not run with docker or singularity on my machine. It looks like it was being run with local python as the default.

**Comment by spficklin** [comment]
It's running just fine on my local machine and Kamiak with singularity.  What kind of message are you getting?

**Comment by spficklin** [comment]
Oh, I may have rebuilt the python image.  If you have it already downloaded, remove it and let Nextflow retrieve it again.

**Comment by spficklin** [comment]
After slack discussion this was just a failed update on the nextflow.config file which @JohnHadish fixed in the `issue-138` branch.
