### ISSUE TITLE
End2End workflow isn't working on example data

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#142]
@bentsherman I tried just testing the end-to-end version of the workflow and it's failing on the local samples for the example data. It seems to do fine with the remote samples.   Can you take a look?

edit: I was using the master branch to test.

**Comment by bentsherman** [comment]
It was a bug with the Kallisto route which hadn't come up because the CI only tests the default aligner. So now that Kallisto is the default, the example script uses Kallisto. It's a small fix so I just pushed it to master.
