### ISSUE TITLE
Error in retrieve_sra.py

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#157]
Line 98 in retrieve_sra.py:
```
if (res['exit'] != 0):
        retry = False
    else:
        print("Aspera Failed. Exit code: {}. Trying https".format(exit_code), file=sys.stderr)
        ec = download_https(urls)
    return ec

```
Needs to be fixed. There may be other errors similar to this.

**Comment by spficklin** [comment]
@JohnHadish .  I'm not sure what the problem is here and this issue is over 1 year old and GEMmaker has been retrieving SRA files just fine.  So, I'm going to close, but please reopen if I'm missing something.
