### ISSUE TITLE
Proposal to change where the "reference_name" currently resides

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#158]
Currently the reference_name resides at the top of the nextflow.config in GEMmaker:
```   
// The unique name for the genome reference assembly. It must not contain
    // spaces or special characters, only alphanumeric characters and underscores.
    reference_name = "CORG"
```
Of the three alignment/pseudo alignment tools, _Hisat2_ is the only one that requires this to be set to a proper name. Kallisto and Salmon will run just fine without it. I personally think it is kind of weird that we pass this name through Kallisto and Salmon. 

I know that the argument for doing this is that it will allow us to see which alignment tool is being used, but the truth is _it does not_. I am currently running rice 475, and all of my files say "CORG" because I forgot to change that variable. In reality, Kallisto and Salmon runs are using the proper rice reference, but they are still being marked as "CORG" in the final name.

My proposal is to move this variable to Hisat2 where it is actually needed, and then remove the naming convention from the files for all processes. 
Currently look like this:
```
SRX1423935_vs_CORG.Kallisto.raw
```
Propose change to this:
```
SRX1423935.Kallisto.raw
```
For ALL alignment tools. 

To me it seems silly and confusing to have this spurious parameter that will more than likely usually incorrectly name files. I think it should just be added to Hisat2.

**Comment by JohnHadish** [comment]
Referencing #124.
This reference is talking about future goals related to this issue.

**Comment by spficklin** [comment]
I think we always need some way to note in the file names what genome reference was used.  Otherwise these files can get copied out of GEMmaker and the context  is lost.

**Comment by spficklin** [comment]
Oh, but if we can implement the idea in #124 then this problem can be resolved via that solution.

**Comment by bentsherman** [comment]
Hey guys, I'm testing GEMmaker for the first time in a while so I've been looking through the changes to `nextflow.config`. Looking at this issue, I was wondering why not use the `reference_name` as the prefix for all of the hisat2/salmon/kallisto input files? It seems that with the example, you have to say `CORG` a lot which means you have to change it a lot when switching to a real dataset. Why not do something like this:
```
    reference_name = "CORG"

    hisat2 {
      enable = false
      index_dir = "${params.input.reference_name}.genome.Hisat2.indexed"
      gtf_file = "${params.input.reference_name}.transcripts.gtf"
    }
    salmon {
      enable = false
      index_dir = "${params.input.reference_name}.transcripts.Salmon.indexed"
    }
    kallisto {
      enable = true
      index_file = "${params.input.reference_name}.transcripts.Kallisto.indexed"
    }
```

I don't really know anything about salmon and kallisto but it seems like this way would be easier to work with.

**Comment by JohnHadish** [comment]
Almost all users will run only one of the three tools, meaning that they are only concerned about modifying one of the sections. 

It is easier to tell the user to "put the index in the directory and add its name to the reference file" than it is to tell them to "split the name into two pieces and enter these in two separate places the reference file after adding the file to the directory". By having this variable separate from the Hisat2 section, it implies that it is needed for Salmon and Kallisto, which it is not.

Adding `reference_name` to the Hisat2 section allows Salmon and Kallisto to be `1 file = 1 configuration parameter` rather than `1 file = 2 configuration parameters in different locations`. Leaving the parameter outside of Hisat2 allows the user to forget about it during the setup, and results in the word "CORG" being added to every file.

Also, see my additional thoughts that will help this on #124 about enforcing that the user modifies the parameters.
