### ISSUE TITLE
The *_2.fastq files are still not being cleaned

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#165]
It appears that the `*_2.fastq` files are still not being deleted during proccessing of samples. They are not being zeroed out. You can see this instance on one of the runs I recently did:

go to:
```
/scidas/John/02-GEMmaker_RiceTest_SizeExampleGraphs/02-Kallisto_Small_GEMmaker
```
run the command:
```
du work -a | sort -n
```

You will get a list of the largest files. All of the largest files are `*_2.fastq` or the directory containing them. 

**Example of portion of output:**
```
9706360	work/4c/1bfeb25f33e950e88ef16cacebba88
9706364	work/cf/9f2a4393f539bdc75c51738ca8ee52
9815360	work/85/4741972699ae9c9ed804763fce328b/SRR2931393_2.fastq
9815360	work/af/7d67beb5eba6c1b5f2692a797f8a77/SRX1424287_2.fastq
9815396	work/85/4741972699ae9c9ed804763fce328b
9815400	work/af/7d67beb5eba6c1b5f2692a797f8a77
9868728	work/8a/fed46b79b06b161571f86461f4dd35/SRX1424387_2.fastq
9868728	work/e4/be4b1e6800509c4b62da2b0cd92832/SRR2931493_2.fastq
9868764	work/e4/be4b1e6800509c4b62da2b0cd92832
9868768	work/8a/fed46b79b06b161571f86461f4dd35
9901288	work/16/008a164d97427161ccb5bbafedac35/SRX1423978_2.fastq
9901288	work/e5/4e474e6d3563015a8735980db8360a/SRR2931084_2.fastq
```

**Comment by spficklin** [comment]
@JohnHadish I believe this is fixed now.  The fix is pushed to the `master` branch.

**Comment by spficklin** [comment]
PR #192  fixes this issue.

**Comment by spficklin** [comment]
This problem is similar enough to #172 and the fix has been applied in the PR that I closed out that issue and just left this one.
