### ISSUE TITLE
Clara Genomics for GPU acceleration

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#166]
NVIDIA released a suite of bioinformatics tools several months ago called [Clara Genomics](https://developer.nvidia.com/Clara-Genomics). I'm not sure if any of the included tools map to the ones that we use like salmon or kallisto, but if they do then they could be incorporated into GEMmaker to accelerate those steps.

Still, someone with better knowledge of genomics tools will have to take a look at this to see if it's relevant. Note that this ecosystem contains both libraries and applications built on top of those libraries, particularly racon, raven, and bonito.

**Comment by spficklin** [comment]
I did a quick check of what they offer. They do have a tool for single cell RNA-Seq analytics.  But that wouldn't apply to all  RNA-seq datasets.  

Given that we have limited time to add new functionality, I'm going to close this out, but I'll add a tag for 'for the future' so we can find it again.

**Comment by spficklin** [comment]
Oh, sorry, I just realized this was meant for discussion, not a feature request.  I'll reopen in case there's more discussion.

**Comment by bentsherman** [comment]
It's okay we can close it. Just wanted to see if it offered anything interesting.
