### ISSUE TITLE
GEMMAKER ProjectID to SampleID metadata/parser broken?

### ISSUE THREAD

**Issue by feltus** [SystemsGenetics/GEMmaker#168]
Hi GEMmaker devs.

[I also sent this issue via email].

Two users Nicole and Rini ran GEMMaker in the last few days and the GEM only had one FPKM column named with the SRX* and not SRA* label.  The dataset was the last in the SRAID.txt list . Both experiments were Arabidopsis.  Rini and Nicole can send the SRAID lists.  

Did something change on the NCBI mappings or the GEMmaker parser? 

Thanks,
Alex

**Comment by spficklin** [comment]
Nothing has changed with parsing of the IDs. Can you post here a snippet of the IDs you provided and those causing issues?

**Comment by spficklin** [comment]
This issue is quite old and we haven't heard more on this. So I'm closing it out.
