### ISSUE TITLE
Failure of workflow during docker image pull causes issues during restart

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#170]
If a GEMmaker run fails while a docker image is being pulled, GEMmaker will not attempt to re-pull the image during restart. Failure does not need to be associated with the attempted pull. 

Upon restart, GEMmaker will attempt to use the **partially pulled image**, and throw this error:

```
Error executing process > 'fastqc_1 (DRX012741)'

Caused by:
  Process `fastqc_1 (DRX012741)` terminated with an error exit status (255)

Command executed:

  fastqc DRX012741_1.fastq

Command exit status:
  255

Command output:
  (empty)

Command error:
  ERROR  : Unknown image format/type: /scidas/arabidopsis_26k/02-create_GEM/04-GEMmaker-40k/work-singularity/gemmaker-fastqc-0.11.7-1.1.img
  ABORT  : Retval = 255
```

It would be nice to have a check to make sure that images were pulled successfully, and retry if they were not.

**Comment by spficklin** [comment]
As this is a Nextflow problem, I'm not sure how we could write code in GEMmaker to check this.   Perhaps this is a good issue to post on the Nextflow Github and we could just document that the problem  could occur on the Troubleshooting page: https://gemmaker.readthedocs.io/en/latest/troubleshooting.html
