### ISSUE TITLE
NCBI no `*_1` file, but has a `*_2`

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#172]
This is more of an inconsistency with NCBI, but it would be possible to fix on our end.

I just encountered a run that has  no `*_1` file, but has a `*_2`.
The run number is: [SRR10915176](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR10915176)
It appears that the culprit file is empty.

This causes GEMmaker to fail, as it believes that it is a paired end file, but in reality there is only 1.

![Image of the bad entry. Appears that one of the read files is empty.](https://user-images.githubusercontent.com/35115540/76486622-1c2f3700-63dd-11ea-96a4-ba691c29716b.png)

**Comment by JohnHadish** [comment]
All runs for this BioProject are that way: [PRJNA602161](https://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR10915176)

**Comment by spficklin** [comment]
This was just fixed in PR #179 and is related to #165 I'm going to close this out as I think it's close enough to #165 that we only need one issue opened.
