### ISSUE TITLE
Some Runs on NCBI have no data

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#173]
Some runs on NCBI have no data: [Example](https://www.ncbi.nlm.nih.gov/sra/ERX1874929[accn])
Currently, this will cause GEMmaker to stop, as there is no way to get around this.
```
2020-03-16T05:21:28 srapath.2.10.0 err: name not found while resolving query within virtual file system module - failed to resolve accession 'ERR1811891' - no data ( 404 )
```

Proposed Solution:
GEMmaker should have a "failed_runs" file that outputs all runs which failed to run, while still continuing. This could be controled by a parameter `ignore_failed_runs = TRUE` in the config.

**Comment by spficklin** [comment]
I believe this issue is fixed with PR #204
