### ISSUE TITLE
Kallisto Bug

### ISSUE THREAD

**Issue by cbmckni** [SystemsGenetics/GEMmaker#174]
Master branch has bug on Kallisto step. Bug is not present on 1.1 with same input.

Bug:

```
[5c/f91b80] Re-submitted process > kallisto (SRR649944)
Error executing process > 'kallisto (2)'

Caused by:
  Process `kallisto (2)` terminated with an error exit status (1)

Command executed:

  kallisto.sh 2 CORG.transcripts.Kallisto.indexed CORG

Command exit status:
  1

Command output:
  (empty)

Work dir:
  /workspace/cole/work/e3/9217c1c4d562683fa1afada70266f8
```

The log file:

```
root@dtp-8547c6ff8b-sw67k:/workspace/cole/work/e3/9217c1c4d562683fa1afada70266f8# cat 2.kallisto.log 

Error: file not found 2.fastq   
```
The file 2_1.fastq was present.

Seems like a fairly simple fix....

**Comment by spficklin** [comment]
Perhaps it's related to this recent fix on the master branch? https://github.com/SystemsGenetics/GEMmaker/commit/f697cb6431d603a8abd8d412e2349c711265744a

**Comment by JohnHadish** [comment]
Yes, this is my bad. I was trying to fix Kallisto so it would accept runs that were "*_2". 

I will roll back these commits if I have to OK to do so.

**Comment by JohnHadish** [comment]
Rolled back
