### ISSUE TITLE
Local Files Should not have to conform to NCBI data naming

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#175]
When running files locally, user should have the option of using whatever style of naming convention that they choose. Currently, the script for running data through each quantification tool assumes NCBI naming conventions:

Kallisto as an example:
```
#!/bin/bash

sample_id="$1"
kallisto_index="$2"
params_input_reference_name="$3"

if [ -e ${sample_id}_2.fastq ]; then
  kallisto quant \
    -i ${kallisto_index} \
    -o ${sample_id}_vs_${params_input_reference_name}.Kallisto.ga \
    ${sample_id}_1.fastq \
    ${sample_id}_2.fastq > ${sample_id}.kallisto.log 2>&1
else
  kallisto quant \
    --single \
    -l 70 \
    -s .0000001 \
    -i ${kallisto_index} \
    -o ${sample_id}_vs_${params_input_reference_name}.Kallisto.ga \
    ${sample_id}_1.fastq > ${sample_id}.kallisto.log 2>&1
fi
```

This means that the user must have everything as `${sample_id}_1.fastq` to run a file. I usually just remove the `_1.fastq`  part of the script when I want to run local files.

**Comment by spficklin** [comment]
So you mean if there are no paired files?  If the files are paired the user has to have some way to differentiate the pairs so I don't see a problem with asking them to name them a certain way.  But you're right... for non-paired data forcing people to but a _1 on the end is annoying.   But that naming scheme is really embedded into alot of GEMmaker.  So, perhaps what we need is an intermediate renaming process that will add the _1 to files for non-paired samples.
