### ISSUE TITLE
Improper Reference directory name results in GEMmaker hanging with no error

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#177]
The name of one of my directories changed, and I forgot to update it in the `nextflow.config`. Upon running GEMmaker, I found that it just hung without giving an error. 

Suggested behavior:
GEMmaker should throw an error that says:
`input_data_dir does not exisit`
This should be implemented for all file paths.

**Comment by spficklin** [comment]
Fixed with PR #205.  The main.nf file now checks that all files/directories in the config files are present.  It also no longer expects files in the `input` folder. FASTQ files can go wherever they want  and the full path is specified in the config.
