### ISSUE TITLE
Issues with retrieve_sra_metadata

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#179]
**1st:** `.command.out` is duplicated in `.command.err` making it difficult to diagnose errors.

**2nd:** Unclear to do upon error. The following is an error received after running arabidposis 26k. It lists the exception as unknown. It would be nice to receive a list of runs which caused issue, as in this case it appears there are only 23 which errored
```
Traceback (most recent call last):
  File "/scidas/arabidopsis_26k/02-create_GEM/05-GEMmaker-26k/bin/retrieve_sra_metadata.py", line 292, in <module>
    download_runs_meta(run_ids, page_size=args.PAGE_SIZE)
  File "/scidas/arabidopsis_26k/02-create_GEM/05-GEMmaker-26k/bin/retrieve_sra_metadata.py", line 120, in download_runs_meta
    raise Exception ('There was an unknown problem retrieving metadata for all of the runs provided: %d != %d. Response: %s' % (num_runs_found, len(run_ids), expstr))
Exception: There was an unknown problem retrieving metadata for all of the runs provided: 26032 != 26055. Response: OrderedDict([ ( 'EXPERIMENT',
                OrderedDict([ ('@alias', 'Leafy'),
```

**3rd:** When performing a massive run, it is rather difficult to diagnose the issue in the `work` directory since there are too many files to even do an `ls`. I think there should be 2 directories, one for json storage, and the other for health of the process. I do not know how we would do this.

**Comment by JohnHadish** [comment]
This type of error was found to be produced when the information on NCBI has changed. It can be (manually) solved by restarting the run with only runs successfully identified as being on NCBI (contained in the `.command.out`) file.

**Comment by spficklin** [comment]
The PR #192 fixes issues 2 and 3 that @JohnHadish raised... plus a whole lot more.

**Comment by spficklin** [comment]
I think this is resolved.  Issue #1 is a nextflow thing and nothing we can control.  So, i'm closing it.
