### ISSUE TITLE
GEMmaker output file is too long

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#180]
The file from standard out is not fun to look at. It is rediculously repetitive. It seems silly to keep what is essentially a screenshot of nextflow ievery second. It would be nice to have GEMmaker overwrite this file each time it updates so it would be readable. Or it can be put back to the old style of Nextflow output which only output 1 line for each process executed.

**Comment by spficklin** [comment]
We don't have the ability to change this. It's a function of Nextflow.  If you use the `-q` flag you can turn off all of that repetitive output.
