### ISSUE TITLE
Data quality Report Additions

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#181]
Loren is interested in data quality statistics that GEMmaker would output at the end.

Average quality statistics that could be output in a table format -- help summarize so this can be added to a paper as information to report quality.

**Comment by spficklin** [comment]
Perhaps some of these might help:

- http://rseqc.sourceforge.net/
- http://qualimap.conesalab.org/
- https://bioconductor.org/packages/release/bioc/html/dupRadar.html
- http://smithlabresearch.org/software/preseq/

**Comment by spficklin** [comment]
Just closing out old issues that aren't getting any traction due to lack of time to work on them and aren't reporting a major problem. I"m labeling "For the future" in case we ever can come back to it.
