### ISSUE TITLE
Documentation about running multiple GEMmaker instances in parallel

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#182]
We have people in our lab who are ramping up their usage of GEMmaker. One issue that has come up is trying to do multiple GEMmaker runs at once. If you try to multiple runs in the same directory that will of course cause issues because of the way that GEMmaker (main.nf) manages state in the work directory. The simple solution is to do each run in separate directories, which is what Nextflow-API does. I think we should add a section to the documentation that talks about this issue, perhaps in troubleshooting or the section about running GEMmaker, because it is a silent error that many new users could encounter.

**Comment by spficklin** [comment]
Hi @bentsherman .  We do have a notice in the documentation that says this.  Take a look and see if you think it needs changing:  https://gemmaker.readthedocs.io/en/latest/before_you_begin.html

**Comment by bentsherman** [comment]
This is perfect, thanks! Sorry I didn't notice it the first time.
