### ISSUE TITLE
Trimmomatic excess variable

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#185]
Trimmomatic does not have a variable called `quality`, but GEMmaker has one. 
```
  software {
    trimmomatic {
      clip_path = "${baseDir}/files/fasta_adapter.txt"
      MINLEN = "0.7"
      quality = ""
      SLIDINGWINDOW = "4:15"
      LEADING = "3"
      TRAILING = "6"
    }
  }
```

**Comment by spficklin** [comment]
It turns out that  `quality` parameter was meant to specify `-phred33`  or `-phred64`. I believe by default trimmomatic uses phred64. So, I think we should rename this argument to `use_phred33` and let the user set it to true or false. Then the workflow can set the -phre33 flag if it's ture.

**Comment by spficklin** [comment]
Issue fixed by PR.
