### ISSUE TITLE
Raise error in trimmomatic process if fasta adapter file is not found

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#186]
The input parameter for the trimmomatic adapter file uses `$baseDir` to find the adapter, but `$baseDir` does not work on Kubernetes. I made a workaround for this in the `k8s` profile which instead provides an absolute path to the adapter file. This approach is still experimental and may fail sometimes. But that revealed a small issue with trimmomatic, which is that if trimmomatic doesn't find the adapter file, it will still run but it will produce incorrect results. So independent of the whole baseDir issue, the trimmomatic process should fail if it can't find the adapter file.

**Comment by spficklin** [comment]
Fixed with PR #205.  The updated `main.nf` file now checks if all files in the config are present.
