### ISSUE TITLE
process fastqc_1 not included in output

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#195]
I am not sure when this was removed. It appears that it has been lost unintentionally, as the code in `main.nf` still runs the code but it is no longer included in the final 'reports' directory. MultiQC is not currently able to find the reports. 

This applies to all three alignment tools, meaning that both Salmon and Kallisto receive no reported fastqc reports, and Hisat only receives a report post trimmomatic (fastqc_2).

**Comment by spficklin** [comment]
I think this issue is fixed.  I'm not sure when it got fixed but I recall this happening but haven't seen it in recent results. So, I'm marking this closed, but reopen if the issue still exists.
