### ISSUE TITLE
nextflow.config is too long

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#198]
The nextflow config is out of hand. I forget to change things, as they are rather buried:
- I do not think that we need time parameters for each individual process. Just one time parameter would be nice.
- Information about schedulers should be placed in seperate files, similar to [Annotator's nextflow.config file](https://github.com/SystemsGenetics/AnnoTater/blob/master/nextflow.config)
- Names of Hisat input files are currently specified in two locations, needs to be condensed

**Comment by spficklin** [comment]
Fixed with PR #205.
