### ISSUE TITLE
GEMmaker should not need to be cloned every time it is ran

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#199]
GEMmaker should be cloned from github one time, and then a user can just use it rather than needing to clone it every single time.

**Comment by bentsherman** [comment]
This is what happens when you run a nextflow pipeline via `nextflow run` like this:
```
nextflow run systemsgenetics/gemmaker
```

Nextflow will clone gemmaker once into `~/.nextflow/assets` and use that copy every time.

**Comment by spficklin** [comment]
I believe what @bentsherman suggests is part of nf-core compatibility  which we should meet (see issue #207 )

**Comment by spficklin** [comment]
This is addressed with the new nf-core compatibility.
