### ISSUE TITLE
Incorrect Identification of Runs and Experiments

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#20]
Some SRX are incorrect and should be multiple SRR. We need to modify the workflow to throw errors.

**Comment by spficklin** [comment]
The solution from our 11/5/18 meeting is to ignore this for now. In our Ath 26K Run experiment this represents only 2K of 17K experiments.  So, we will deal with this after we get through the full experiment.

**Comment by spficklin** [comment]
Marking as an issue to try to address for the v1.1 release.

**Comment by spficklin** [comment]
I'm going to close this out.  There's no good way, without a lot of effort (and we're limited on time) to catch these from NCBI.
