### ISSUE TITLE
`clean_work_files.sh` fails on restart

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#202]
It appears that information not intended for `clean_work_files.sh` is being passed to it:

Error in output file:
```
Error executing process > 'clean_trimmed_fastq (HC_2_19_056_S23_R1_001)'

Caused by:
  No signature of method: java.lang.Integer.join() is applicable for argument types: (String) values: [ ]
Possible solutions: wait(), find(), wait(long), min(int, int), print(java.lang.Object), print(java.io.PrintWriter)

Source block:
  flist = files_list[0].join(" ")
  """
    clean_work_files.sh "${flist}"
    """

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

```

Finding the directory for this specific instance run is rather difficult with the current command output for GEMmaker (See Here: #203 ), but here is an example that I was able to find that appears to show that alot of unneccesary information is being passed to the clean_work_files.sh script:

`.command.sh` output:
```
#!/bin/bash -ue
clean_work_files.sh "scidas John 08-Apple_Maturity_Project 02-GEMmaker work db cbb802cd101d4625a0c93050f06172 CC_1_19_074_S15_R1_001_1u_trim.fastq"
```

**Comment by spficklin** [comment]
I'm going to close this out because this `clean_work_files.sh` script isn't part of GEMmaker and just a side-script used to help clean up when a job fails. But with the most recent PR, I think the need for this script is gone.
