### ISSUE TITLE
Singularity cache directory not defined

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#209]
An update to singularity that allows the user to select the singularity directory causes GEMmaker to throw a Warning:

```
Pulling Singularity image docker://gemmaker/python:3.8.5-1.2 [cache /scidas/John/GEMmaker_05_1/work/singularity/gemmaker-python-3.8.5-1.2.img]
Pulling Singularity image docker://gemmaker/base:1.1 [cache /scidas/John/GEMmaker_05_1/work/singularity/gemmaker-base-1.1.img]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /scidas/John/GEMmaker_05_1/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
```

I agree that it is fine if we let user select where files are cached, but I think it should be implemented in a way that by default they are cached in a specific area. The majority of users will not care where the files are cached, and this warning will cause them confusion.

**Comment by spficklin** [comment]
The setting was removed in PR #200.  But I get these warnings too  the first time I use singularity.  I have noticed that Nextflow is not using the images directly from cache, but creating a copy of them into the `works/singularity` folder anyway.  

I'm wondering if we should add back in the setting for the cache directory. Thoughts @bentsherman

**Comment by spficklin** [comment]
That makes sense.  I think we can add a note to the documentation letting folks know about this behavior.
