### ISSUE TITLE
Normalization Script

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#21]
We need a GEM normalization python script to be added to GEMmaker.

**Comment by bentsherman** [comment]
Hey you guys should know that we're working on a tool in the Feltus lab called [GEMprep](https://github.com/feltus/GEM_PREP) which will include a Python script for GEM normalization (log2 transform, KS-test outlier removal, quantile normalization, in whatever combination you want). We should have it done pretty soon.

**Comment by spficklin** [comment]
Oh, great to know @bentsherman!

**Comment by bentsherman** [comment]
Normalization script is now available at the GEMprep repo, closing this issue.
