### ISSUE TITLE
Home directory reference "~/" not recognized

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#219]
GEMmaker does not recognize paths which use the standard linux home directory path reference (~/) :

If we use this path for Salmon index:
```
 ~/Documents/00-reference/Reference.Salmon.indexed/
```

We get this:
```
Quantification:
---------------
  Tool:                       salmon
  Salmon Index Directory:     ~/Documents/00-reference/Reference.Salmon.indexed/
  
Error: Salmon Index Directory does not exist or is empty! Please Check that you have the proper references, that they are placed in the reference directory, and they are named properly.    
GEMmaker is missing the following file: '~/Documents/00-reference/Reference.Salmon.indexed/' (where '*' is the name of your organism)

 -- Check script 'main.nf' at line: 166 or see '.nextflow.log' file for more details
```

Works if path is changed to:
```
/home/usr/Documents/00-reference/Reference.Salmon.indexed/
```

**Comment by spficklin** [comment]
I'm not sure it's worth trying to make GEMmaker deal with the `~` because the code uses the Groovy functions for checking paths so Groovy doesn't seem to support it.   Unless we want to dig into Groovy deeper.  Maybe the best idea is to make a note in the documentation telling users to use full paths.

**Comment by spficklin** [comment]
I did a bit more poking around .I can't see that Groovy supports the tilda in relative file paths. We'd have to do some regular expressions to support it and make a substitution.  I'm going to close this out for lack of time to work on it (as it's not a major bug).  @JohnHadish if you want to provide a fix then please reopen.
