### ISSUE TITLE
Documentation for dev branch (currently nf-core branch) does not have install information

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#221]
The documentation for the dev branch does not tell the user how to install GEMmaker on the [Installation](https://gemmaker.readthedocs.io/en/dev/installation.html) page. It just has Dependencies and Container information. 

The user will probably not be familiar with nf-core programs, so they will not understand that GEMmaker will automatically be installed. I think that we should have a blurb about this to make it clear:

Suggested:
```
When running GEMmaker for the first time, all neccesary files will be downloaded and automatically installed on your machine.
```

We should also add information about versions for Singularity, as we used to only accept version 2.6 or before, but now require a version 3.

**Comment by spficklin** [comment]
This has been resolved with the merged PR.
