### ISSUE TITLE
GEM ordering 

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#224]
A user requested that the final GEM should be ordered in the same was as the input text file. For example:

Input file:
```
SRA0001
SRA0003
SRA0004
```

Should produce a GEM like this:
```
          SRA0001   SRA0003   SRA0004
Gene1
Gene2
Gene...
```
For local files, I propose that it be based alphabetically.

**Comment by spficklin** [comment]
What if a user doesn't bother to put the SRRs in an order, or mixes them up?   The SRRs aren't the same as the sample names.

**Comment by spficklin** [comment]
This seems to be low priority and maybe not something we have time to deal with. I'm going to mark this as `for the future` so it doesn't hang out in our issue queue forever. But @JohnHadish if you have time and want to tackle it, please reopen.
