### ISSUE TITLE
Use multi-threading in trimmomatic

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#23]
It looks like trimmomatic is the longest part of this workflow, and trimmomatic supports multi-threading but it's not being used in the workflow. Can we incorporate multi-threading without altering the results?

**Comment by spficklin** [comment]
Yes we can.  It was left as non multi-threaded because every CPU is being used by other jobs which are also running trimmomatic.  So we may see speedup on individual runs but overall if all the CPUs/cores/threads are busy from other jobs I'm not sure we'd see a difference.

**Comment by bentsherman** [comment]
I see, so it may not be useful for your system on Kamiak. In that case I can add a config argument to specify the number of threads.

**Comment by spficklin** [comment]
@bentsherman this has been done, right?  Is it already merged or part of an existing PR?
