### ISSUE TITLE
Information about setting singularity/docker cache dir 

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#230]
GEMmaker does not mention anything about setting the cachedir for singularity/docker. By default, the current behavior has the cachedir within the directory that GEMmaker is executed first. This results in the following `WARN` message being displayed:

```
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /home/jah/Documents/12-KI_csGCN_Detection/02-GEMmaker/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
```

I am of the opinion that we should add documentation to address this, so that the user is not concerned about WARN messages when they run the test data in GEMmaker for the first time.

Proposed documentation -- at the bottom of "TEST GEMMAKER":
```
When running Singularity, GEMmaker will throw a warning saying that your  cachedir is not set. It will then default to the work directoiry. If you intend to run GEMmaker multipe times, you may wish to designate a perminant cache directory for the GEMmaker docker files. We suggest that you store them in a base singularity directory. This can be done by adding this line to your `~/.bashrc` file:
"""
export NXF_SINGULARITY_CACHEDIR=$HOME/.singularity/cache
"""

This  will prevent  the need to pull the images each time GEMmaker is run in a new directory
```

**Comment by spficklin** [comment]
A new addition has been added to the documentation to help folks with this.
