### ISSUE TITLE
Nextflow/GEMmaker does not automatically pull new material

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#232]
Nextflow stores GEMmaker in the directory `${HOME}/.nextflow/assets/systemsgenetics/gemmaker`
It does not update GEMmaker automatically when GEMmaker is run in a different project. 

Nextflow warns you if you are not on the master branch, and has you designate your desired branch:
```
Project `systemsgenetics/gemmaker` currently is sticked on revision: dev -- you need to specify explicitly a revision with the option `-r` to use it
/var/spool/slurmd/job32370455/slurm_script: line 17: --max_cpus: command not found
```

But once you designate a branch, it does not automatically pull any updates. 

To update, user must go to `${HOME}/.nextflow/assets/systemsgenetics/gemmaker` and perform a `git pull` command.

**Comment by spficklin** [comment]
This is a Nextflow functionality, I don't think we  can make GEMmaker do anything about it.  Although we can put a notice in the Troubleshooting section of the documentation.

**Comment by spficklin** [comment]
The documentation has been updated to help folks with this.
