### ISSUE TITLE
Preliminary files clean-up not working

### ISSUE THREAD

**Issue by fmobegi** [SystemsGenetics/GEMmaker#235]
# Am running this command :
```
nextflow run systemsgenetics/gemmaker -profile docker   -resume   --pipeline hisat2   --hisat2_base_name Ascochyta_rabiei_ArME14   --hisat2_index_dir /data/reference_genomes/ME14   --hisat2_gtf_file /data/reference_genomes/Ascochyta_rabiei_ArME14.gtf   --input "*_{R1,R2}.fq.gz"   --trimmomatic_clip_file /data/TruSeq3-PE.fa --trimmomatic_keep_trimmed_fastq false --hisat2_keep_bam false --hisat2_keep_sam false --publish_multiqc_report true --max_cpu 14
N E X T F L O W  ~  version 20.07.1
Launching `systemsgenetics/gemmaker` [mighty_kare] - revision: bea01d59ea [master]
WARN: It appears you have never run this project before -- Option `-resume` is ignored
------------------------------------------------------
                                        ,--./,-.
        ___     __   __   __   ___     /,-._.--~'
  |\ | |__  __ /  ` /  \ |__) |__         }  {
  | \| |       \__, \__/ |  \ |___     \`-._,-`-,
                                        `._,._,'
  Compatible Workflow 
  systemsgenetics/gemmaker v2.0.0
------------------------------------------------------
WARN: Found unexpected parameters:
* --max_cpu: 14
- Ignore this warning: params.schema_ignore_params = "max_cpu" 

Workflow Information:
---------------------
  Project Directory:          /home/ubuntu/.nextflow/assets/systemsgenetics/gemmaker
  Work Directory:             /data/01_raw_data/ascochyta_rabiei/work
  Launch Directory:           /data/01_raw_data/ascochyta_rabiei
  Config Files:               [/home/ubuntu/.nextflow/assets/systemsgenetics/gemmaker/nextflow.config, /data/01_raw_data/ascochyta_rabiei/nextflow.config]
  Container Engine:           docker
  Profile(s):                 docker
Samples:
--------
  Remote sample list path:    
  Local sample glob:          *_{R1,R2}.fq.gz
  Skip samples file:          
Reports
-------
  Report directory:           /data/01_raw_data/ascochyta_rabiei/results/reports
Quantification:
---------------
  Tool:                       hisat2
  Hisat2 Index Base Name:     Ascochyta_rabiei_ArME14
  Hisat2 GTF File:            /data/reference_genomes/Ascochyta_rabiei_ArME14.gtf
  Hisat2 Index Directory:     /data/reference_genomes/ME14

  Trimmomatic Parameters:
     clip path:               /data/01_raw_data/TruSeq3-PE.fa
     MINLEN:                  0.7
     SLIDINGWINDOW:           4:15
     LEADING:                 3
     TRAILING:                6
  
Published Results:
---------------
  Output Dir:                 /data/01_raw_data/ascochyta_rabiei/results/GEMs 


  Output Dir:                 /data/01_raw_data/ascochyta_rabiei/results/GEMs
  FPKM counts:                Yes
  Raw counts:                 Yes
  GEM file:                   Yes

executor >  local (1137)
executor >  local (1137)
[-        ] process > retrieve_sra_metadata                             -
[a5/985395] process > write_stage_files (Tween_E_1_L003)                [100%] 86 of 86 ✔
[04/3632fb] process > get_software_versions                             [100%] 1 of 1 ✔
[59/6ca499] process > start_first_batch                                 [100%] 1 of 1 ✔
[74/402a6e] process > read_sample_file (MER_17_373_E_2_L003.sample.csv) [100%] 81 of 81
[12/c3f57a] process > next_sample (TR6417_L_2_L004)                     [100%] 71 of 71
[-        ] process > download_runs                                     -
[-        ] process > fastq_dump                                        -
[-        ] process > fastq_merge                                       -
[05/9ee11c] process > fastqc_1 (TR6417_iv_2_L004)                       [100%] 81 of 81
[-        ] process > kallisto                                          -
[-        ] process > kallisto_tpm                                      -
[-        ] process > salmon                                            -
[-        ] process > salmon_tpm                                        -
[75/a8bca6] process > trimmomatic (MER_17_378_L_3_L003)                 [ 98%] 79 of 81
[e2/b1fd5f] process > fastqc_2 (MER_17_378_L_3_L003)                    [ 96%] 76 of 79
[9f/3441b4] process > hisat2 (MER_17_378_L_3_L003)                      [ 94%] 74 of 79
[5c/0b56fa] process > samtools_sort (ME14_E_2_L004)                     [100%] 74 of 74, failed: 2
[bd/d24400] process > samtools_index (ME14_E_1_L004)                    [100%] 72 of 72
[72/c38346] process > stringtie (ME14_E_1_L004)                         [ 99%] 71 of 72
[f6/c1c66b] process > hisat2_fpkm_tpm (TR6417_L_2_L004)                 [100%] 71 of 71
[-        ] process > multiqc                                           -
[-        ] process > create_gem                                        -
[-        ] process > failed_run_report                                 -
[-        ] process > clean_sra                                         -
[-        ] process > clean_fastq                                       -
[-        ] process > clean_merged_fastq                                -
[59/253c8a] process > clean_trimmed_fastq (ME14_E_2_L004)               [100%] 74 of 74
[0f/6c8cc6] process > clean_sam (ME14_E_1_L004)                         [100%] 72 of 72
[cd/89353e] process > clean_bam (TR6417_L_2_L004)                       [100%] 71 of 71
[-        ] process > clean_kallisto_ga                                 -
[-        ] process > clean_salmon_ga                                   -
[53/faed43] process > clean_stringtie_ga (TR6417_L_2_L004)              [100%] 71 of 71
Error executing process > 'samtools_sort (MER_17_378_iv_3_L003)'
Caused by:
  Process `samtools_sort (MER_17_378_iv_3_L003)` terminated with an error exit status (1)
Command executed:
  echo "#TRACE sample_id=MER_17_378_iv_3_L003"
  echo "#TRACE sam_lines=`cat *.sam | wc -l`"
    samtools sort     -o MER_17_378_iv_3_L003.bam     -O bam     -T temp     MER_17_378_iv_3_L003.sam
Command exit status:
  1
Command output:
  #TRACE sample_id=MER_17_378_iv_3_L003
  #TRACE sam_lines=81843641

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  [bam_sort_core] merging from 32 files and 1 in-memory blocks...
  [E::bgzf_flush] File write failed (wrong size)
  samtools sort: failed writing to "MER_17_378_iv_3_L003.bam": No space left on device
  [E::bgzf_close] File write failed

```
## I have about 3.5T of storage space and input data averaging about 4G per PE-sequenced sample and 186 samples in total. 
 `1.3G    TR9571_L_3_L003_R1.fq.gz
1.4G    TR9571_L_3_L003_R2.fq.gz
1.3G    TR9571_L_3_L004_R1.fq.gz
1.4G    TR9571_L_3_L004_R2.fq.gz
2.0G    TR9571_iv_1_L003_R1.fq.gz
2.1G    TR9571_iv_1_L003_R2.fq.gz
2.0G    TR9571_iv_1_L004_R1.fq.gz
2.1G    TR9571_iv_1_L004_R2.fq.gz
`
Am trying to be efficient with space usage so I intend to clean up fastqc, trimmomatic, sam/bam files for all all fully processed samples. 

However, with the command above, every time I get to 50-60 samples processed, and cleanup_status at100%, all residual files for all the analyses are still there:

```
find work/ -name "*.bam" -type f -exec ls -lh {} \; | head -n 5
-rw-r--r-- 1 ubuntu ubuntu 2.6G Jul  6 20:29 work/59/6754c38024282f8e13470f435e62f3/ME14_E_2_L003.bam
-rw-r--r-- 1 ubuntu ubuntu 2.3G Jul  6 17:57 work/12/3e8584d02b897fbc65c16374d27222/TR9571_iv_3_L004.bam
-rw-r--r-- 1 ubuntu ubuntu 3.0G Jul  6 18:28 work/19/72a997d55cecb2fc2e703230256379/TR9571_L_1_L003.bam
-rw-r--r-- 1 ubuntu ubuntu 2.7G Jul  6 21:47 work/19/afc4c2e73c5407a92a90f66c0a9b32/TR6417_L_2_L003.bam
-rw-r--r-- 1 ubuntu ubuntu 3.2G Jul  6 20:26 work/67/b0dd5fb77c7a47cbc135c70959f0b4/MER_17_373_L_3_L003.bam
###########
find work/ -name "*.sam" -type f -exec ls -lh {} \; | head -n 5
-rw-r--r-- 1 ubuntu ubuntu 16G Jul  7 00:54 work/d4/5af5b111e4671607fc1f88f5f9f5fd/TR6417_L_2_L004.sam
-rw-r--r-- 1 ubuntu ubuntu 29G Jul  7 00:42 work/99/863f80e803271864de2707e0263c9d/TR9571_iv_1_L003.sam
-rw-r--r-- 1 ubuntu ubuntu 24G Jul  6 23:13 work/e3/20ca6db11bb6be8bf76f82317f6cb3/TR6417_iv_1_L003.sam
-rw-r--r-- 1 ubuntu ubuntu 14G Jul  6 21:35 work/fc/3d214c75d8da6346f14c6490250a2b/MER_17_378_E_1_L003.sam
-rw-r--r-- 1 ubuntu ubuntu 17G Jul  7 01:20 work/08/014c87e8c3e3620ae3f3d4042057ef/ME14_E_1_L004.sam
```

**Comment by JohnHadish** [comment]
Hello @fmobegi 

GEMmaker implements a system to allow cleaning of files while still allowing restarts. To acheive this with Nextflow, we had to perform a work-arround that removes the *contents* of the file while keeping their *name, size, and location*. These files appear on your machine, but do not actually take up space. 

If you look at the contents of one of the files you mentioned:

```
cat work/59/6754c38024282f8e13470f435e62f3/ME14_E_2_L003.bam
```
You should see that the file is actually empty (no text is shown). This is the intended behavior, and these files do not take up space on your system even though they appear to when looked at in a given directory. This is just our current work arround for allowing nextflow to restart in case the run is interrupted.

## Fix
However, judging from this portion of your error report:
```
Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  [bam_sort_core] merging from 32 files and 1 in-memory blocks...
  [E::bgzf_flush] File write failed (wrong size)
  samtools sort: failed writing to "MER_17_378_iv_3_L003.bam": No space left on device
  [E::bgzf_close] File write failed
```
 it appears that your issue is probably not related to the actual amount of storage on your system, but is rather related to how your system has docker set up, and how much memory is allocated to running docker commands.

To attempt to fix this, please follow the first 2 sections ("cgroup memory limits" and "Validate cgroup settings") from this post on  [Docker](https://fabianlee.org/2020/01/18/docker-placing-limits-on-container-memory-using-cgroups/) -- approx 3 minute read.


I hope this fixes the issue. If it does not, could you send me information about what  system you are using and how you have docker implemented? This will help with further troubleshooting. 

---
Alternatively, we can get GEMmaker running with Singularity on your computer. In my experience, Singularity tends to run smoother than Docker. You will run GEMmaker in the same way, except that `-profile docker` will be replaced in your command with `-profile singularity`. Information on Installing Singularity can be found here: [Install Singularity](https://sylabs.io/guides/3.0/user-guide/installation.html)

Cheers,  
John

**Comment by fmobegi** [comment]
Thank you John for the pro tips. 
I started the tasks from scratch using singularity after deleting all files from the previous run. 
Unfortunately, I have the same problems. 
I have also checked the residual files that you said should be empty and all of them have their content intact. 

See these files: 
[check.completed.sam.txt](https://github.com/SystemsGenetics/GEMmaker/files/6782884/check.completed.sam.txt)
[check.completed.bam.txt](https://github.com/SystemsGenetics/GEMmaker/files/6782885/check.completed.bam.txt)

Just a result of a dirty loop and view ```for i in $(find work/ -name "*.bam" -type f); do ls -lh $i; samtools view $i | head -n 2; done > check.completed.txt```

**Comment by spficklin** [comment]
Hi @fmobegi thanks for reporting the issue!  I'm testing now to see if we have a bug that might have been worked in.  Sorry for the slow reply. Summer vacations have slowed us down.

**Comment by spficklin** [comment]
So, I just ran a test and BAM files cleaned up just fine.  So, something must have been different at your end to prevent cleanup.  If you can help us figure out what that would be helpful.

One way that I do know of that GEMmaker will fail to cleanup files is if GEMmaker gets interrupted. On a cluster this can happen if your requested run time is exceeded and the scheduler preempts the job.  Unfortunately, Nextflow ignores previous steps that didn't completes and starts over and GEMmaker can't detect where those folder are.    On a local machine, if you stopped GEMmaker and then restarted it, this could happen as well.   But if your run was not preempted before GEMmaker could finish then there's something else going on.

**Comment by fmobegi** [comment]
Thanks for the continued support. Sorry, I forgot to report back to you. After cleaning up everything and rerunning the job, everything runs smoothly now. Turns out there was unscheduled system maintenance which could have caused my problems.

**Comment by spficklin** [comment]
Great! Thanks for letting us know
