### ISSUE TITLE
Easy RE-start on Failed runs

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#237]
GEMmaker currently adds failed runs to an HTML report, and does nothing else. Most of the time, these runs fail diue to an issue with NCBI.

Most users will want to try to run these again. If they did not implement a retry, this will need to be done after the first GEMmaker run completes. If they do not want to re-run the entire run, they are forced to copy-paste and create a new SRA.txt file to re-run.

It would be nice if there was a failed runs file which could just be used as this file, rather than dealing with the html file. Currently the HTML file is not user friendly to copy from, due to multiple columns and unneccesary $ signs:

![image](https://user-images.githubusercontent.com/35115540/124817122-3835e080-df1e-11eb-8afd-b7f82795c2a6.png)

When copied from HTML:
```
$SRR2931055 | $SRX1423949 | $Failed to fetch sample url.
-- | -- | --
$SRR2931063 | $SRX1423957 | $Failed to fetch sample url.
$SRR2931062 | $SRX1423956 | $Failed to fetch sample url.
$SRR2931065 | $SRX1423959 | $Failed to fetch sample url.
$SRR2931068 | $SRX1423962 | $Failed to fetch sample url.
$SRR2931069 | $SRX1423963 | $Failed to fetch sample url.
$SRR2931083 | $SRX1423977 | $Failed to fetch sample url.
$SRR2931084 | $SRX1423978 | $Failed to fetch sample url.
$SRR2931086 | $SRX1423980 | $Failed to fetch sample url.
$SRR2931079 | $SRX1423973 | $Failed to fetch sample url.
$SRR2931077 | $SRX1423971 | $Failed to fetch sample url.
$SRR2931087 | $SRX1423981 | $Failed to fetch sample url.
$SRR2931080 | $SRX1423974 | $Failed to fetch sample url.
$SRR2931045 | $SRX1423939 | $Failed to fetch sample url.
$SRR2931050
```

I could either write a bash command to get the list of failed runs, or manually modify this list by deleting unnecesary information. Would be nice if the failed run file had a partner that looked like this:

```
SRR2931063
SRR2931062
SRR2931065 
SRR2931068 
SRR2931069
SRR2931083
SRR2931084
SRR2931086
SRR2931079
SRR2931077
SRR2931087 
SRR2931080 
SRR2931045 
SRR2931050
```

**Comment by spficklin** [comment]
Yeah, good idea.  An easy to read list of failed SRRs would be good.

**Comment by spficklin** [comment]
We've not addressed this in a long time, and we're lacking time at this point so I'm closing this out.
