### ISSUE TITLE
Missing elements to look at in parse_sample_metadata.py

### ISSUE THREAD

**Issue by cwytko** [SystemsGenetics/GEMmaker#24]
Unhandled sample attribute: 'ecotype', value: Columbia; Col-0
Unhandled sample attribute: 'tissue_type', value: pool: flowers and 10 day seedlings

**Comment by spficklin** [comment]
For 'ecotype' we can use the term EFO:0000434: http://www.ebi.ac.uk/efo/EFO_0000434

for 'tissue_type' we can use the term NCIT:C12801: http://purl.obolibrary.org/obo/NCIT_C12801

Can you update the script to handle those two?

**Comment by spficklin** [comment]
This is quite old, and we may handle metadata differnetly.
