### ISSUE TITLE
GEMmaker is "failing" according to front page of github

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#248]
The first screen people see when visiting the site says that "GEMmaker is failing":

![Screenshot from 2021-11-18 11-40-15](https://user-images.githubusercontent.com/35115540/142485525-e6a7fb58-6574-4eb9-ab9b-910e2952f916.png)

This appears to be due to linting errors with respect to nfCore compliance

**Comment by JohnHadish** [comment]
It appears that we are out of date with nf-core aspects. Our "linting file" `.nf-core-lint.yml` no longer registers with nf-core

**Comment by spficklin** [comment]
Yeah, nf-core changes their testing process and we just haven't updated GEMmaker yet.  someone needs to take the time to do it :-)

**Comment by spficklin** [comment]
Fixed
