### ISSUE TITLE
Reference more prominent

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#25]
To set the reference genome settings for the current veresion of GEMmaker we have to scroll down to the hisat2 configuration section in the nextflow.confg file.  I have forgotten to make that setting change several times.  I propose we move the reference settings back up to the input array at the time and use those values in hisat2.  That way the most critical settings are at the top and less critical settings needed for tweaking are in the software_params section.

**Comment by bentsherman** [comment]
I may go ahead and address this issue in the multithreading PR because I'm gonna have to move around some params anyway.

**Comment by bentsherman** [comment]
This issue was handled by the multithreading PR.
