### ISSUE TITLE
Hisat2 unmapped read optional cleanup

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#255]
Hisat2 has a feature where unmapped reads are assigned to a file of the users choice using the parameter `--un`. In GEMmaker, this file is `${sample_id}_un.fastq`. 

Currently, these files are kept, with no cleanup for them present. These files are fairly small, but an edge case scenario could result in them expanding. 

This is a low priority request to add functionality that would add a parameter to clean up these files.

**Comment by spficklin** [comment]
I believe this has been fixed in the current version.
