### ISSUE TITLE
Edge Case Fastq Merge

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#259]
### Description of the bug

Edge Case, potentially can be considered as incorrect entering of data into NCBI. For project [PRJNA605000](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA605000) researchers used two technologies to produce 3 fastq files for each sample (1 NextSeq & 1 HiSeq with 2 lanes). This causes GEMmaker to fail during fastq merge since it is not expecting a NextSeq run in addition to the two HiSeq runs. 

Directory:
```
SRR11029259_1.fastq
SRR11029259_2.fastq
SRR11029259_3.fastq
SRR11029260_1.fastq
SRR11029260_2.fastq
SRR11029260_3.fastq
SRR11029261_1.fastq
SRR11029261_2.fastq
SRR11029261_3.fastq
SRR11029262_1.fastq
SRR11029262_2.fastq
SRR11029262_3.fastq
SRR11029263_1.fastq
SRR11029263_2.fastq
SRR11029263_3.fastq
SRR11029265_1.fastq
SRR11029265_2.fastq
SRR11029265_3.fastq
SRX7681625_1.fastq
SRX7681625_2.fastq
```

Would be relatively easy to detect when this edge case happens. Probably not neccesary since it is very specific.

**Comment by JohnHadish** [comment]
https://www.ncbi.nlm.nih.gov/bioproject/PRJNA473012

**Comment by spficklin** [comment]
Just closing out old issues that aren't getting any traction due to lack of time to work on them and aren't reporting a major problem. I"m labeling "For the future" in case we ever can come back to it.
