### ISSUE TITLE
Report of Default Memory, time, etc.

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#261]
### Description of feature

GEMmaker will occasionally encounter memory errors when it encounters large files:
```
#TRACE sample_id=SRX9369046
#TRACE fastq_lines=0
Ran out of memory for SRX9369046_1.fastq
java.lang.OutOfMemoryError: Java heap space
```
Unfortuently, GEMmaker does not report what default parameters for each process is, and how much memory was used that triggered the error. 

It would be nice to have a feature that says something like:
```
Ran out of memory for SRX9369046_1.fastq - Exceeded limit of 8GB
```
So that parameters can easily be adjjsted, rather than relying on a trial and error or a code deep dive.

**Comment by spficklin** [comment]
That particular java heap space images usually means the FASTQ file is corrupted and the memory limit error is a bit misleading.  We don't generally encounter this except when GEMmaker has a bug and crashes in the middle of a run and the cleanup removed a file that was still needed.   This is a bit old so I'm going to close it out.
