### ISSUE TITLE
Output GEM format is not tidy

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#265]
### Description of feature

The output GEM format is not in the tidy format recognized by most other programs (everything except base r and KINC). We should consider changing this format. The only change that would be needed would be to change the first column from a rowname format to one where the gene name is considered a column as well. We would want to coordinate KINC with this as well.

While this would still not technically be *True* Tidy format, I think it would make it easier for users wanting to use the GEM in other programs. 

Current format:
```
           Sample1 Sample 2 Sample3
Gene1       1              2            3
Gene2       2              3            4
Gene3       5              6            7
```

Proposed format:
```
gene    Sample1 Sample 2 Sample3
Gene1       1              2            3
Gene2       2              3            4
Gene3       5              6            7
```

True Tidy Format:
```
gene     sample     count
Gene1  Sample1     1
Gene2  Sample1     2
Gene3  Sample1     3
Gene1  Sample1     2
Gene2  Sample1     3
Gene3  Sample1     4
Gene1  Sample1     5
Gene2  Sample1     6
Gene3  Sample1     7
```

**Comment by spficklin** [comment]
Just closing out old issues that aren't getting any traction due to lack of time to work on them and aren't reporting a major problem. I"m labeling "For the future" in case we ever can come back to it.
