### ISSUE TITLE
GEMmaker no longer creates nextflow reports by default

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#267]
### Description of feature

GEMmaker used to automatically produce the summary, timeline, and trace reports by default. The user must now request these to be run manually. 

[GEMmaker Documentation on Reports](https://gemmaker.readthedocs.io/en/latest/results.html?highlight=timeline#timeline-report)
[Nextflow Documentation](https://www.nextflow.io/docs/latest/config.html)

What needs to be added back in:
```
trace {
    enabled = true
    file = 'pipeline_trace.txt'
    fields = 'task_id,name,status,exit,realtime,%cpu,rss'
}
```

**Comment by spficklin** [comment]
I recently ran GEMmaker and got these files in the `results/pipeline_info` directory:

```
execution_report_2022-11-06_16-53-56.html    
execution_trace_2022-11-06_16-53-56.txt
execution_timeline_2022-11-06_16-53-56.html  
pipeline_dag_2022-11-06_16-53-56.svg
```

Are these the files you are missing?

**Comment by JohnHadish** [comment]
Yes, those are the missing files. Do you have your submission script for that run?

**Comment by spficklin** [comment]
I don't think this is a problem any longer.  closing out.
