### ISSUE TITLE
Fail on resume due to file not being present in stage directory

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#268]
### Description of the bug

GEMmaker stopped due to an unrelated issue with a file format. After fixing that issue, I restarted GEMmaker. GEMmaker then gave this error:
```
No such file: /scidas/unmigrated/John/18-Random_Forest_Arabidopsis_Attributes/04-GEMmaker/03-KAMIAK/work/GEMmaker/stage/SRX7267319.sample.csv
``` 
which is an issue with the Staging File. I located the file, whcih was in the `process` directory and moved it to the `stage`. This did not solve the issue. Apon restart GEMmaker returned the file to the `process` file and threw the same error.

The file in the incorrect directory was not related to the initial error, and I suspect that GEMmaker was just stopped at an unfortunate time where it thinks the file should be in `process` but actually needs it in `stage`.

Banaided my GEMmaker run by telling GEMmaker to ignore this file.

Note: Not using most recent version of GEMmaker, but when looking at difference between versions nothing related to

**Comment by spficklin** [comment]
We've not had this issue in a very log time. I'm going to close this out, but please reopen if this is still an issue.
