### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by cbmckni** [SystemsGenetics/GEMmaker#29]
Some users(such as myself) are running GEMmaker with a new Python3 installation ,which does not have many packages(such as pandas, xmltodict, etc) that are needed for the scripts in GEMmaker. To make installing these dependencies easy, please include a requirements.txt file somewhere in the directory. I'm sure y'all have used them before, but in case you want to read up on them you can here: https://pip.pypa.io/en/stable/user_guide/#id1

This will ensure all the required packages(as well as their correct versions) will be easy to install using Pip.

**Comment by spficklin** [comment]
@cwytko can you add this in for @cbmckni ?

**Comment by cwytko** [comment]
See bdef314
@cbmckni is this sufficient?

**Comment by cbmckni** [comment]
@cwytko Looks like it! Thanks!
