### ISSUE TITLE
The issue of offset of 33 vs 64

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#34]
NCBI uses standard sanger FASTQ offset (also know as phred 33) for their sra archive.

Please reference this paper:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2847217/

Excerpt from Second to last paragraph:
"We also note that the NCBI SRA makes all its data available as standard Sanger FASTQ files (even if originally from a Solexa/Illumina machine). We hope that this trend will lead to Illumina themselves switching to the original FASTQ convention at a later date, which would eventually relegate this confusion of incompatible variants to a historical concern."

**Comment by JohnHadish** [comment]
Documentation for fastq dump:
https://ncbi.github.io/sra-tools/fastq-dump.html

**Comment by spficklin** [comment]
We should be sure to add this detail to the documentation or FAQ in case someone who uses GEMmaker has the same questions

**Comment by JohnHadish** [comment]
Should be closed when 34-docs is merged with master

**Comment by spficklin** [comment]
Docs merged.
