### ISSUE TITLE
GEMmaker v1.0 release:  expected versions

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#35]
For our GEMmaker v1.0 release we should list the compatible versions, and these should be used in GEMmaker-docker as well:

1. SRA Toolkit v2.8.0
2. FastQC v0.11.7
3. Trimmomatic v.0.38
4. Hisat2 v2.1.0
5. Stringtie v1.3.4d
6. Samtools v1.9
7. NextFlow v0.26.4

Please note, these may not be the most recent  versions. If you are using a more recent version please reply

**Comment by bentsherman** [comment]
We should probably go ahead and bump the nextflow version requirement to 18.10 because they added a PBS Pro executor which works better with Palmetto so I'm probably going to update the PBS profile to use that.

And yes, nextflow jumped from v0.32 to v18.10.

**Comment by spficklin** [comment]
Assigning to @biggstd because it's part of the #38 issue.

**Comment by spficklin** [comment]
I'm closing this. I think for documentation we should emphasis running with Docker/Singularity rather than expect the user to install all of that software.
