### ISSUE TITLE
Update workflow to use GEMmaker-docker

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#38]
The workflow should be updated so that it uses the GEMmaker-docker Docker image for all processes.  This will mean that even on local installations (i.e. Kamiak or Palmetto) that the docker image will be used rather than relying on local installation of software.  This has the advantage that 

1.  We are guaranteed to always use the same software versions and modules
2.  It ensures we can run nextflow on local HPC systems, OSG, and in the SciDAS SciApp

**Comment by biggstd** [comment]
I have modified the workflow and the configuration to be able to use docker and singularity.

This involved some config file shuffling.

The simplest way to test this is to:

```bash
# Clone the appropriate branch:
git clone -b issue_38_docker_integration https://github.com/SystemsGenetics/GEMmaker.git
# On Kamiak I need to load the singularity module.
# There is a bug with the newest version (3.0) that will be fixed upon the next release.
module load singularity/2.4.2
#  Copy the config.
cp nextflow.config.example nextflow.config
# Run the workflow with the desired profiles.
nextflow run main.nf -profile testing,inSingularity
# With Docker:
nextflow run main.nf -profile testing,inDocker

# On Kamiak with singularity:
# You will need to create the kamiak profile for this to work.
nextflow run main.nf -profile kamiak,inSingularity
```

This may be slow the first time as it has to pull all the images.

I am testing on kamiak right now.

**Comment by bentsherman** [comment]
I think we can still allow the user to choose whether to use docker images using the `-with-docker` command line option. We would just need to add this line to the config file:
```
process.container = systemsgenetics/gemmaker
```

Or whatever the dockerhub name is.

Also, why are we developing separate docker images for each dependency in addition to GEMmaker-docker? I don't really see the advantage, it's just more configuration and it will probably slow down the workflow if a bunch of different images have to be pulled from dockerhub.

**Comment by spficklin** [comment]
Hi @bentsherman .  We've got some preliminary docker integration working.   I'm hoping we'll have something ready for you to test by tomorrow... fingers crossed.

**Comment by bentsherman** [comment]
Awesome, looking forward to testing it.

As a side note, I guess we don't really need GEMmaker-docker as a separate repository. We could just store the Dockerfile(s) here. The Docker image also doesn't really need to use Lmod, it could just install all of the dependencies to the default system paths and that would be it. Just putting these thoughts here for reference.

**Comment by spficklin** [comment]
> As a side note, I guess we don't really need GEMmaker-docker as a separate repository. We could just store the Dockerfile(s) here. The Docker image also doesn't really need to use Lmod, it could just install all of the dependencies to the default system paths and that would be it. Just putting these thoughts here for reference.

Yep, that's the approach we're taking.

**Comment by spficklin** [comment]
Hey @bentsherman there is  pull request #62 that has the docker integration if you could test it for us!

**Comment by bentsherman** [comment]
Awesome I will test ASAP!

**Comment by bentsherman** [comment]
This feature works now, closing.
