### ISSUE TITLE
Handling Sample Failure

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#39]
if a sample fails at any step, it should, perhaps not cause the entire workflow to fail.  Two examples include

1)  A single sample cannot be downloaded at the first step.
2)  A sample contains garbage reads such that trimmomatic cannot determine what the encoding format is.

Rather, the workflow should simply report which samples failed and continue.

**Comment by spficklin** [comment]
Should we add this as a release-blocker for v1.0 release?  Or just deal with the problems on a case-by-case basis?

**Comment by biggstd** [comment]
It turns out this should be an easy fix. 

```
errorStrategy { task.attempt==1 ? 'retry' : 'ignore' }
```

The question then is to which processes this should be applied to, and if the number of attempts should be in the `nextflow.config` file or not.

**Comment by bentsherman** [comment]
We could put it in each of the profiles in the config file to apply it to all processes, I think we're already doing that with `errorStrategy` and `maxRetries`.

**Comment by spficklin** [comment]
I agree we could do it at each process.

**Comment by bentsherman** [comment]
This feature was merged a while back, closing.

**Comment by spficklin** [comment]
I'm reopening this issue because PR #102 rolls back the fix we made for this.

**Comment by spficklin** [comment]
I think perhaps what we could do is created a 'failed' folder in the `work/GEMmaker/` directory.  If the download fails we move the file in the failed folder.  This might make it easy later to find those that didn't work and try to diagnose them.

**Comment by bentsherman** [comment]
I should point out that the execution report (and also the trace report) gives the status of every process, so we can also use that to query for the samples that failed.

**Comment by spficklin** [comment]
I'm closing this for now because we don't have time to deal with it.  We can reopen if this becomes a serious problem again. Some of the fixes we're making will help prevent some of these failures in other places.

**Comment by spficklin** [comment]
Many of these issue were fixed by converting for loops and hopefully if statements as described in #138
