### ISSUE TITLE
Some code was added that breaks things when ran on Kamiak

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#49]
There was some code added that causes GEMmaker not to work on Kamiak. I assume that it is being used for something else, and has been tested on another system, but it won't work on the slurm cluster. It is paramerters like:
```
withLabel: "!multithreaded"
```
I commented them out and it works again.

**Comment by JohnHadish** [comment]
It looks like it was during this commit:
commit 5a15b7cc04341ee03d6fe6de2c5cf005ec98d005

@bentsherman I was wondering what this code is used for?

**Comment by bentsherman** [comment]
I think @cwytko had that issue and he fixed it by upgrading nextflow to 0.32.

**Comment by cwytko** [comment]
@JohnHadish see here to force nextflow to upgrade

https://www.nextflow.io/docs/latest/faq.html#how-do-i-use-a-specific-version-of-nextflow

run the command in the terminal as normal

**Comment by spficklin** [comment]
@JohnHadish we can update Nextflow on Kamiak so closing this out.
