### ISSUE TITLE
Outputs of trimmomatic process not recognized as cached on resume run

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#51]
I've had to resume some nextflow runs a few times now due to power outages on Palmetto, and in every case I was waiting on a few trimmomatic processes to finish. However, when I resume the run, nextflow always reruns trimmomatic for all samples even though 99% of them should have been cached. As a result I'm still trying to process Ath chunk 12.

I'm not as familiar with the input/output dependencies of the various processes, but I'm guessing that the outputs of the trimmomatic process are not being recognized on a resume run. But I don't see why they shouldn't be able to be cached.

If all trimmomatic processes completed, then I think nextflow caches them correctly. I think it's only when a few are incomplete that nextflow reruns all samples. Do the outputs have to be merged somehow?

**Comment by spficklin** [comment]
No outputs aren't merged. It should recognize when one finishes and not re-run them all....  That's odd behavior.  @JohnHadish or @biggstd have you noticed that before?

**Comment by bentsherman** [comment]
I just resumed again and it looks like all of the trimmomatic processes were cached properly, only two were re-submitted. I think my earlier issues might have been due to some I/O problems I was having on Palmetto. So now I'm pretty confident that nextflow is doing the right thing here.
