### ISSUE TITLE
Too many requests

### ISSUE THREAD

**Issue by biggstd** [SystemsGenetics/GEMmaker#52]
It remains to be seen if this is more from us blasting their servers while we try to work this out, or if this will be a persistent problem for users. 

```
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```

A possible method is implementing a backoff solution, like [this one](https://github.com/litl/backoff]).

**Comment by spficklin** [comment]
Are you getting this error during metadata collection for each sample?

**Comment by biggstd** [comment]
This error is persistent for me. We need to consider how to either rate-limit these requests, or perhaps submit one bulk request.

**Comment by spficklin** [comment]
Ideas:
1. Is it possible to apply the `queue_size` argument on the executor to limit the number of jobs for this process to a small enough number that it doesn't overwhelm the NCBI server?
2.  We may have to do a bulk retrieval of metadata into one large file and then have a later process parse out the results for each sample/experiment individually.

**Comment by bentsherman** [comment]
This issue seems to be related to #31. If we provide the two-column input then nextflow will only have to download metadata for each SRX instead of each SRR, or possibly download metadata for all SRX IDs at once if that's possible.

**Comment by spficklin** [comment]
Yes, that's correct.  Once we get the two column format input file we can move the metadata download to another part of the workflow and perhaps do it in bulk rather than for each sample.

**Comment by spficklin** [comment]
This issue has been resolved with the most recent PR.
