### ISSUE TITLE
Troubleshooting Document

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#55]
We should include in our documentation a Troubleshooting section to help people who encounter common mistakes.  

Here's one:
Error Message:
> ERROR ~ Cannot get property 'remote_list_path' on null object

Resolution:  You forgot to rename nextflow.config.example to nextflow.config

**Comment by spficklin** [comment]
Another troubleshooting gotcha:

> 
>  [Actor Thread 17] ERROR nextflow.processor.TaskProcessor - Error executing process > 'SRR_to_sample_id (S5)'
> 
> Caused by:
>   No signature of method: _nf_script_0849f927.users() is applicable for argument types: (ConfigObject) values: [[:]]
> Possible solutions: use([Ljava.lang.Object;), every(), grep(), every(groovy.lang.Closure), use(java.util.List, groovy.lang.Closure), use(java.lang.Class, groovy.lang.Closure)

Solution:  Change the slurm queue from 'users queue' to what your queue is.

**Comment by spficklin** [comment]
We probably should add a troubleshooting section to the docs before we release.   that second issue no longer exists, but the first does.

**Comment by bentsherman** [comment]
I'll try my hand at this... should be pretty easy to add a basic troubleshooting page to the docs.

**Comment by bentsherman** [comment]
I'm also going through the documentation and fixing typos and other errors, trying to make everything clean and professional...

**Comment by bentsherman** [comment]
Okay think I'm done cleaning up. Anyway, we now have a troubleshooting page.
