### ISSUE TITLE
Salmon and Kallisto output different genes that hisat2

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#60]
This is due to the fact that salmon and kallisto require a transcipts file and Hisat does not. The transcript file is generated using the Tophat command:
```
gtf_to_fasta TAIR10_Araport11.gtf TAIR10_Araport11.fna TAIR10_Araport11.transcripts
```
This does not generate the same genes that Hisat does, even though both are using the same .gtf and .fna files. This needs investigating.

**Comment by spficklin** [comment]
I think it's okay to close this out.  Nothing we can do.  We just need to keep it in mind.
