### ISSUE TITLE
Error with fastq-dump on Palmetto

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#63]
I mentioned this issue on Slack, duplicating here now that I've zoomed in on the problem. The `fastq-dump` tool just kinda stopped working on Palmetto. For example, when running the RemoteRunExample:
```bash
$ fastq-dump --split-files SRR649944
2018-12-21T04:01:39 fastq-dump.2.8.2 err: item not found while constructing within virtual database module - the path 'SRR649944' cannot be opened as database or table
```

Ashwin is currently investigating, I think it might be a Palmetto-specific issue, but I'm reposting here just for reference.

**Comment by spficklin** [comment]
@bentsherman do you still have this issue given that we are using Docker images?

**Comment by bentsherman** [comment]
Yes oddly enough, which increases my suspicion that there is a problem between Palmetto and fastq-dump.

**Comment by bentsherman** [comment]
I've been going back and forth with Ashwin and we suspect that this issue has something to do with Palmetto's networking. Ashwin was able to avoid the error by using one of Palmetto's data-transfer nodes, which have fewer networking restrictions, so he is looking into it.

As a side note, we have had some success with version 2.3.3 of sratoolkit. However, even that version still fails for some SRR IDs, including (conveniently) many samples in the Ath experiment.

**Comment by spficklin** [comment]
Tyler is working on an aspera process to replace the sratoolkit so hopefully that will help resolve these issues.  Issue #47

**Comment by bentsherman** [comment]
The aspera branch pretty much made this a non-issue so I'm closing.
