### ISSUE TITLE
script create_GEM.py does not work with examples now

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#70]
The ``--prefix`` needs to be rewritten, appears to currently only finds "SRX" numbers when command:
```
python create_GEM.py --sources {PWD}/output --prefix "" --type TPM
```
is ran.
The examples now run as "1", "2" and "3"

**Comment by spficklin** [comment]
Fixed in current master branch.  There is a new createGEM process.
