### ISSUE TITLE
Change pipeline script to use environment variable for work directory

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#76]
These staging files are being written to the `work` directory but the name of that directory actually comes from the environment variable `NXF_WORK`. The pipeline script needs to be updated to use that variable in case the user changes the name of the work directory.

**Comment by spficklin** [comment]
Oh! Good catch.

**Comment by spficklin** [comment]
I committed a fix for this.  All places where `work` was hardcoded now use the variable `${NXF_WORK}`

**Comment by spficklin** [comment]
I'm reopening this. It seems the fix broke Travis CI integration.  The NXF_WORK variable is used but only if it's defined. If it is not define it is not used.

**Comment by bentsherman** [comment]
Awesome, looks like it works now.
