### ISSUE TITLE
Process each sample end-to-end with a single process

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#78]
After some discussion with @feltus about performance considerations with nextflow, I have an idea. It would be a significant change to GEMmaker, although not necessarily difficult, and it could bring several benefits.

I observed that all of the processes from `fastq_dump` to `fpkm_or_tpm` are tied to a specific sample. In particular, now that we provide experiment IDs alongside run IDs, the pipeline for each sample is simply to run through each of those processes. This means that we could replace these processes with a single process like so:
```
process process_sample {
  // directives ...

  input:
    set val(sample_id), val(run_ids), val(type) from SAMPLES

  output:
    set val(sample_id), file "*.fpkm" into FPKM_FILES

  script:
  """
  # download SRA files
  # extract FASTQ files
  # merge FASTQ files
  # trim FASTQ files
  # ...
  # produce FPKM / TPM files
  """
}
```

Some of the benefits of this approach:
- First and foremost, each step in the pipeline will execute on the same node which means that __we can use local scratch__ instead of NFS, and without having to transfer files aside from what is published.
- We can control the parallelism with `queueSize` alone, that is, if the queue size is 100 then there will never be more than 100 samples' worth of scratch space being used because each job in the queue spans the entire processing pipeline. That means we could __eliminate all of the chunking code__.
- Only published files are copied back to shared storage, which means that intermediate files won't take up storage space, __eliminating all of the cleanup code__.

What would it take to implement:
- All of the afore-mentioned processes must be combined into one process with a big script
- Any branching (salmon / kallisto / hisat, fpkm / tpm) must be handled in bash instead of nextflow
- The docker images must be combined into a single image containing all dependencies

So overall I think this change could fix a lot of major problems and greatly reduce the complexity of our pipeline script. The main effort would probably be refactoring the branches of the pipeline into a bash script, particularly the salmon / kallisto / hisat branches. I'd like to try this out for myself so I'll probably create a branch for it soon.

**Comment by biggstd** [comment]
Can you elaborate on 'performance considerations' and 'major problems'? Is there major trouble with the amount of NFS overhead?

**Comment by spficklin** [comment]
My preference would be to leave each tool as a separate process and not lump them as a single process.  I think if one tool fails it's easier to diagnose and pick up where it left off.  For example, if something fails towards the end, the process will have to start all over again.

**Comment by bentsherman** [comment]
I don't know all of the details of your system on Kamiak, but on Palmetto the shared scratch storage is the greatest bottleneck of this workflow by far. Especially if we aren't saving any FASTQ files, we could easily process hundreds of samples at a time, but at present it isn't feasible because everything is done on shared storage, which means that we are limited both in terms of storage space (all of the intermediate files for each sample) and disk bandwidth (all of the jobs interacting with shared storage). For example, I predict the entire Ath26k experiment would take 1-2 months to process end-to-end assuming no failures. I think this time could be cut dramatically on a large cluster, but only with this change in place. That pretty much sums up the "major problems" I dealt with last semester in trying to run that experiment on Palmetto. These problems have been solved in part by the chunking code and cleanup code, but at the cost of greatly increased code complexity, and the fact remains that everything is done in shared storage.

As for your point Stephen, yes that would be a downside of this approach. But the way I see it, either you have a few samples in which case the workflow won't take long either way, or you have many samples (like us) in which case it won't make much difference if a few samples fail. If more than a few fail then there's probably a systemic problem anyway. And for what it's worth, in my experience failures tend to happen towards the beginning, when the workflow has to download things.

**Comment by spficklin** [comment]
Maybe this is a conversation we need to have as a group to decide how best to handle it.  We don't seem to have the issues on Kamiak that you're encountering on Plametto.  But GEMmaker is meant to be run on HPC systems so I would like to see it run well on Plametto.  

In terms of timing to get the experiment done.  We have been meaning to try running GEMmaker on OSG now that all the tools are in singularity.   I wonder how it would perform there....

**Comment by bentsherman** [comment]
Well for the time being I've created a branch so that I can play with this on Palmetto. It's a separate pipeline script which is compatible with the original config file and uses it's own combined docker image, so all of the original functionality is still there. I've already captured most of the workflow in this new script, if I observe some performance benefit with it on Palmetto then I'll let you know.

**Comment by spficklin** [comment]
I'm good with including this new script into GEMmaker but one thing that may happen is that the two methods get out of sync.  For example, we change a setting in the main.nf but forget to make the same change in the new one. I think what may be best is to move all of the bash scripts out into template files and then we can use the same template files in each one?  This way we only have one copy of each step's bash code.  But, can you use multiple templates in one process?  That's what I think you'd need to do.

I'm going to mark this for further consideration for release v1.1

**Comment by bentsherman** [comment]
Yeah I don't think templates would work, they would have to be scripts with arguments so that you could pass in nextflow variables. Another thought I had was to also test `main-e2e.nf` in the travis CI... that would at least ensure that the e2e script works at the very least. Fortunately it's designed to work with the same config file so we wouldn't have to duplicate that.

At some point I might go ahead and make a "discussion" PR so that it's easy to see what the changes look like.

**Comment by spficklin** [comment]
>Yeah I don't think templates would work

I'm not sure I understand why they wouldn't work  (See docs here: https://www.nextflow.io/docs/latest/process.html#template).  Can you elaborate?

**Comment by bentsherman** [comment]
Well originally I thought it wouldn't work because it doesn't look like you can have multiple templates in a process. But after reading the docs again, it looks like you can also call templates like regular bash scripts, which means that the e2e process could just call the templates in sequence. So maybe we can make templates work if we write them correctly. I will try this when I have time.

**Comment by spficklin** [comment]
@bentsherman what do you think of adding a chunking feature instead of trying to lump everything into one big process.  For example, break up the FASTQ file into smaller pieces that can be moved across the network faster?

I think this would allow you to not bring Palmetto networking to its knees (maybe) and would allow the workflow to keep it's processes intact, which feels more comfortable to me.

**Comment by bentsherman** [comment]
I'm not sure, I'd have to think about it. The goal is to be able to process up to hundreds of samples at a time, so there are still hundreds of processes interacting with shared storage at the same time. Even if you chunk the FASTQ files into smaller pieces, I don't see how that would decrease the disk traffic while the files are being processed.

**Comment by spficklin** [comment]
I think it depends how long it takes to process each chunk.  The network activity will decrease during processing.  So rather than moving 200GB of data at once over tens of minutes, you move 2GB at a time over a few minutes and those moves may stagger as processing proceeds differently for each chunk.

**Comment by bentsherman** [comment]
Yeah that makes sense. I think I'll have to just try a few different things and measure them. Right now I'm dealing with other issues between Palmetto and GEMmaker, but after that I'd like to actually compare the two methods as they are and see (1) how much time is spent doing file transfers and (2) whether the e2e method actually gives any speedup.
