### ISSUE TITLE
Cleanup of failed folders

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#80]
Using the newest GEMmaker when I run the 475 rice dataset the `output` directory only cosumes 1.9GB of storage.  Previously all of the output would have consumed around 30TB of storage.  So this is great!

However, we still have some problems with the `work` directory.  If GEMmaker fails along the way and has partially created files (e.g. SAM/BAM/FASTQ files) then restarts the process it creates a new process directory so those failed attempts never get cleaned up.  Also, any temp files (e.g. `temp.*.sam`) files don't get cleaned up either.    So, while the `output` directory has 1.9GB, the `work` directory in my case is still consuming 5TB.  

Note, that work directories may be abandoned if any part of GEMmaker fails.  For example, if you are running 100 samples and 1 failes for some reason, all of those working directories for the other 99 samples are potentially abandoned (need to verify this).

Perhaps the solution is to run a 'cleanup' process if the `-resume` flag is used that can look for incompleted work directories.  However, I have no clue how to determine which directories contain results from failed processes.

**Comment by bentsherman** [comment]
Nextflow provides two directives, `beforeScript` and `afterScript`, which allows you to run arbitrary scripts before and after a process. We could create "pre" and "post" scripts that simply create an empty file in the work directory and then delete it to signify that the process completed:
```
# pre-script
touch _PROCESS_INCOMPLETE

# execute process...

# post-script
rm _PROCESS_INCOMPLETE

Then it would be easy to scan for orphaned work directories. We could create a cleanup process like you said or we could use the `onError` handler:
```
workflow.onError {
  // remove orphaned work directories
}
```

The latter option would have to be written in Groovy instead of Bash though.

**Comment by JohnHadish** [comment]
https://github.com/nextflow-io/nextflow/issues/1126

Potentially reason why some were failing

**Comment by spficklin** [comment]
exit 141 is commonly a SIGPIPE error meaning that a pipe was shutdown in the middle of the next tool in the piped command reading from the pipe.  I'm getting 141 errors on other processes too, so I don't think this problem is specific to downloading SRAs.  I'm currently wrapping the SRA download into a Python script so we have greater control over problems with it. For example, prefetch will sometimes indicate that the download failed when it fact it has not.  I'm not sure why. Maybe some last bit of communication didn't happen correctly for it. 

This may help resolve the 141 on this too as I suspect it may have something to do with the for loop in the bash code?

**Comment by spficklin** [comment]
Oh, and I should mention the Python wrapper script I'm writing will cleanup the files if it detects a failure :-)

**Comment by spficklin** [comment]
We've done all we can do to fix this issue.  The new python scripts created for issue #138 will cleanup failed attempts for downloading SRAs and failed fastq_dump runs.  We have processes to do cleanup. We just need to wait on Nextflow to provide more control.
