### ISSUE TITLE
retrieve_SRA_metadata.py fails for Ath26k experiment

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#85]
I haven't been able to run the Ath26k experiment using the latest GEMmaker. The past few times that I've tried, I've gotten this error from the metadata script:
```
ERROR ~ Error executing process > 'retrieve_sample_metadata'

Caused by:
  Process `retrieve_sample_metadata` terminated with an error exit status (1)

Command executed:

  retrieve_SRA_metadata.py /scratch4/btsheal/GEMmaker/Ath26k/SRA-ID/SRA_IDs.14.txt

Command exit status:
  1

Command output:
  (empty)

Command error:
  Traceback (most recent call last):
    File "/scratch4/btsheal/GEMmaker/bin/retrieve_SRA_metadata.py", line 288, in <module>
      download_runs_meta(File)
    File "/scratch4/btsheal/GEMmaker/bin/retrieve_SRA_metadata.py", line 74, in download_runs_meta
      response_obj = urllib.request.urlopen(request)
    File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
      return opener.open(url, data, timeout)
    File "/usr/lib/python3.5/urllib/request.py", line 472, in open
      response = meth(req, response)
    File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
      'http', request, response, code, msg, hdrs)
    File "/usr/lib/python3.5/urllib/request.py", line 510, in error
      return self._call_chain(*args)
    File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
      result = func(*args)
    File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
      raise HTTPError(req.full_url, code, msg, hdrs, fp)
  urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

This example was with chunk 14. But I don't have this problem for the unit test, so I think there's a problem that occurs with `retrieve_SRA_metadata.py` for a larger number of samples. I'm not familiar with that script but I would guess that there is either something wrong with the request URL that is constructed or that we are hitting some limit on the capabilities of this API endpoint.

**Comment by spficklin** [comment]
Can you find out what is the last SRR written to the output file?

**Comment by bentsherman** [comment]
So at this point it looks like this script works fine for Ath chunk 14, on both Palmetto and my local machine. But I'm still getting this error for the combined chunks (1-10, 11-20, 21-27), even when I decrease the page size.

Now that I'm looking at it I think I see a potential cause -- when the script queries NCBI it always includes the entire list of IDs in the request, even though it's only grabbing 100 at a time. It would be much more sensible to only include 100 (or however many) IDs and get rid of the page / page size logic. I will implement this and a few other changes and if it works I'll push them.

**Comment by bentsherman** [comment]
I think I fixed this issue with the latest commits. Also fixed a few more issues that I hit while testing on some of the other Ath chunks. Closing this issue.

**Comment by spficklin** [comment]
If it was sending all the IDs then that was a bug.  Thanks for fixing it.
