### ISSUE TITLE
Provide SRX and SRR IDs in the SRA ID file

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#86]
After working on the `retrieve_SRA_metadata.py`, it seems to me that this script is downloading more data than it needs to. If I understand correctly, for each run ID it downloads the entire metadata for the corresponding experiment ID. I hate to bring this up right before our release, but why not provide the SRX / SRR mapping from the start? Isn't that the original form of the SRA IDs anyway? That way we would only have to download each SRX metadata once instead of multiple times for each run. For the Ath experiment that would probably cut the download time in half. I only bring it up because it seems to represent a large fraction of the runtime for this script.

**Comment by spficklin** [comment]
There's been no further discussion on this so I'm closing to clean up older issues.  If this is still a bother to you @bentsherman please reopen and we can chat more.
