### ISSUE TITLE
Error retrieving meta data

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#88]
I'm getting the following error:

```
  Traceback (most recent call last):
    File "/scidas/arabidopsis/Ath_26k/02-GEMmaker-attempt_two/bin/retrieve-sra-metadata.py", line 261, in <module>
      download_runs_meta(run_ids, page_size=args.PAGE_SIZE)
    File "/scidas/arabidopsis/Ath_26k/02-GEMmaker-attempt_two/bin/retrieve-sra-metadata.py", line 83, in download_runs_meta
      save_ncbi_meta(experiment, sample, run)
    File "/scidas/arabidopsis/Ath_26k/02-GEMmaker-attempt_two/bin/retrieve-sra-metadata.py", line 112, in save_ncbi_meta
      run_id = run["@accession"]
  TypeError: list indices must be integers or slices, not str

Work dir:
  /scidas/arabidopsis/Ath_26k/02-GEMmaker-attempt_two/work/51/5247249106d404b9afd7031f251752

```

**Comment by biggstd** [comment]
A list is created, then re-assigned in a loop here:
https://github.com/SystemsGenetics/GEMmaker/blob/master/bin/retrieve-sra-metadata.py#L80

I guess a dictionary `{}` should to be there?

**Comment by spficklin** [comment]
So the problem is that the `run` argument is empty.  The problem is that the run named `SRR2927685` doesn't exist on NCBI, but it's in our 26K Ath experiment file.  So, the etuils ignores it and does not include it in the output returned.  That effectively makes this for loop incorrect (I think): 

https://github.com/SystemsGenetics/GEMmaker/blob/73c703de020437a416d79149ddd93481f6180749/bin/retrieve-sra-metadata.py#L64-L67

I believe that `zip` assumes that there will always be an experiment for each run, but this isn't the case. I'm going to revert some code to fix this.

**Comment by spficklin** [comment]
Should be fixed with recent PR
