### ISSUE TITLE
Problems with images and Singularity

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#97]
When I try to run GEMmaker with Aspera 3.8.1 I get this error message:

`/home/gemdocker/.aspera/connect/bin/ascp: No such file or directory`

The problem is that on Kamiak the `/home` directory is automatically bound via a system-wide configuration file to be mounted.  That covers up our /home/gemdocker folder where aspera is installed and it's not usable.  

This could be a problem with any of our Docker images because ever site has the freedom to automatically bind a directory by default in singularity.   Perhaps we should use a /gemmaker directory in our images and store the software there.  This way we won't ever conflict with a system-wide setup.

**Comment by bentsherman** [comment]
I think the best thing here would be to modify the Dockerfile to move the aspera installation to `/opt/aspera`, as that is a standard place to install custom software.
