### ISSUE TITLE
Missing reference indexes causes GEMmaker to hang

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#99]
If you run GEMmaker and forget to create your genome index files or if you give an incorrect directory in your `nextflow.config` file then GEMmaker will run just fine until it gets to the read quantification step (e.g. hisat2/salmon/kallisto) and then just hang. It doesn't give any errors and doesn't proceed.  This is because it's waiting for the channel to provide the reference files which never happens.  

So, we should probably add a check to the main.nf to make sure those files are present and if not then fail.

**Comment by spficklin** [comment]
@JohnHadish the fix for this is merged but I noticed it gotmerged into the branch for issue #109. Was that intentional?

**Comment by JohnHadish** [comment]
I believe so? I believe that there was another pull request out at that time that had conflicts with 99 and 109 that made more sense to deal with in on a side branch rather than the main

**Comment by JohnHadish** [comment]
I just investigated the code, and 99 has changed from the time I wrote that code. We are using a different method for assigning the reference file names now. This should not be merged to main due to this.

**Comment by spficklin** [comment]
So your fix then to check for missing references, should you redo that so we can marge it into the master branch?

**Comment by JohnHadish** [comment]
Yep, I am redoing now

**Comment by spficklin** [comment]
I believe this issue is fixed as per the merged PR.  Closing
